services:
  php-fpm:
    build:
      context: .
      dockerfile: Docker/php-fpm/Dockerfile
    container_name: symfony_php_fpm
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: dev
    # ports:
    #   - "8084:8080"
    networks:
      - symfony

  nginx:
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    container_name: symfony_nginx
    # # image: nginx:alpine
    # volumes:
    #   - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./project:/var/www/html
    ports:
      - "8084:80"
    depends_on:
      - php-fpm
    networks:
      - symfony

  db:
    image: mysql:8.0.32
    container_name: symfony_db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  # Link to phpmyadmin
  # http://localhost:38080/
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: symfony_phpmyadmin
    links:
      - db
    restart: always
    ports:
      - "38080:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    networks:
      - symfony

  redis:
    container_name: symfony_redis
    image:          redis:3.0.7
    command:        ["redis-server", "--appendonly yes"]
    ports :
      - "16379:6379"
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
